### ISSUE TITLE
Provide online test on personal page

### ISSUE THREAD

**Issue by tflidd** [jaark/twofactor_yubikey#1]
It would be great to provide a test on your personal page where you can test if everything is properly set up. Once it fails, you are not able to login without admin-intervention.
I had encountered this error: https://github.com/nextcloud/server/issues/1957

**Comment by Tarry91** [comment]
I believe this issue can be closed with the changes done in #5.

**Comment by sullenx** [comment]
I agree. Since the Yubikeys can only be registered if it passes at least 1 OTP, this essentially would be the test. Closing down this issue.
