### ISSUE TITLE
Nextcloud 14 compatibility

### ISSUE THREAD

**Issue by ChristophWurst** [jaark/twofactor_yubikey#12]
Hello app maintainers,

we made some changes to the Nextcloud 2FA logic that requires 2FA providers to populate their enabled/disabled state to the Nextcloud server, a.k.a *[making 2FA providers stateful](https://github.com/nextcloud/server/pull/9632)*. Before this change, the Nextcloud server used to load all provider apps and ask them if they are enabled for a given user. Since this doesn't work when an app is (temporarily) disabled or fails to load, we now use a *registry* that persists this state. In addition to a small performance improvement, this will allow us to enhance the 2FA mechanism for Nextcloud 15.

Please see the server changes at https://github.com/nextcloud/server/pull/9632 and update your app so that it registers the provider's state on the `IRegistry` whenever it changes.

As a reference implementation, you might find it helpful to check out the following apps which have been updated for this breaking change:
* https://github.com/nextcloud/twofactor_u2f
* https://github.com/nextcloud/twofactor_totp
* https://github.com/nextcloud/server/tree/master/apps/twofactor_backupcodes

Let me know if you need more info about the required changes :wink: 

Thanks for developing a 2FA provider for Nextcloud :rocket: :cloud: :closed_lock_with_key:

**Comment by jaark** [comment]
Thanks for the heads-up.

What is the timescales for when this will be required?
I am currently moving house and won't be able to do anything on this for at least a couple of weeks. Will that delay likely cause issues for end users?

**Comment by ChristophWurst** [comment]
Hi @jaark,

this will be a requirement for Nextcloud 14, which will be released in a few weeks.

> I am currently moving house and won't be able to do anything on this for at least a couple of weeks

No problem, I will help you with the migration and send a pull request.

**Comment by Tarry91** [comment]
Nextcloud 14 is out today. Please merge the pull request as soon as possible and publish the updated version to the appstore.

**Comment by jaark** [comment]
I've published the signed version here but the App Store seems to be having a few issues at the moment and times out whilst I'm trying to upload the release.

I'll give it another try tomorrow.
