### ISSUE TITLE
enforce 2FA by admin

### ISSUE THREAD

**Issue by audiosquare** [jaark/twofactor_yubikey#14]
it would be good to have the option to enforce 2FA by admin. The reason behind is that security rules must be save without any option by users to deactivate.

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/server/issues/2348#issuecomment-418077727.

**Comment by jaark** [comment]
The sensible place to enforce such a thing is within the nextcloud core, not an individual TFA extension.
