### ISSUE TITLE
Fix usage of deprecated API

### ISSUE THREAD

**Issue by ChristophWurst** [jaark/twofactor_yubikey#15]
Deprecation notice https://github.com/nextcloud/server/blob/d07c5db947ebe04666e18294481ff3574314f625/core/js/config.js#L23

Usage https://github.com/jaark/twofactor_yubikey/blob/e7e75855cbb7ab2fe7b8823eb113325ca5eb486f/js/settings-admin.js#L16

**Comment by jaark** [comment]
Changed API usage.
