### ISSUE TITLE
NextCloud 15 compatibility

### ISSUE THREAD

**Issue by Libre4IT** [jaark/twofactor_yubikey#17]
Would someone be able to make this app compatible with NextCloud 15? 
After upgrading to NC15 twofactor_yubikey cannot be enabled.

**Comment by fischli** [comment]
The max-version inside appinfo/info.xml is limited to 14. You may try to fix it on your own by setting it to 15. Can't say if it's sufficient ... worth trying.

**Comment by Libre4IT** [comment]
Setting max-version to 15 works. Updated info.xml in this project as well.

**Comment by jaark** [comment]
Thanks for catching this.
Updated the app in apps.nextcloud.com
