### ISSUE TITLE
Don't allow adding of new yubikeys if no (working) ClientID/SecretID in Admin menu is set

### ISSUE THREAD

**Issue by Tarry91** [jaark/twofactor_yubikey#5]
The title says it all. It would be great, if users wouldn't be allowed to add yubikeys if the API settings are not (properly) filled out by the admin.

Currently it is allowed to add keys and the two factor authentification is enabled but fails. The users is locked out.

EDIT: maybe just check the OTP when a new yubikey is added. I belive that this is recommended by yubico anyway. If the OTP cannot be checked or the OTP is not valid do not add the new credential and show an error message that they should talk to the admin or something.

**Comment by sullenx** [comment]
@Tarry91 - I was thinking of the same thing. Just verify the OTP during the add. Also, I was thinking adding a way for the admin to verify a test OTP from the admin menu, it can help in debugging.

**Comment by sullenx** [comment]
@Tarry91 - I added a field for admin to verify OTP tokens, this way they can verify the configuration. I also added a warning about user getting locked out if the configuration is not valid. 

I added the logic to the user key registration. Now the OTP is verified before the key is registered.

Please let me know if this addresses this issue.

**Comment by Tarry91** [comment]
@sullenx works just fine on Firefox 57! Thank you.

If you want to use the admin menu OTP test for debugging maybe it is helpful to print the response from the authentification server? I think it might help to understand why an OTP has been rejeceted, if you cannot get it to work.

**Comment by sullenx** [comment]
@Tarry91  Debug info is a good idea, but going through the execution class, it doesn't return much (only errors i see there is for invalid response and error).

I don't know how GitHub tracks feature request, but let's put that as one for next release. It's likely that we'd just output information to the nextcloud logs directly. 

Let me know if we are good to close this issue.

**Comment by Tarry91** [comment]
No problem. I agree, that this is better tracked in an seperate issue, as the main problem of this issue is already dealt with.
