### ISSUE TITLE
Link to yubico in admin menu

### ISSUE THREAD

**Issue by Tarry91** [jaark/twofactor_yubikey#7]
It would be helpful to link to the yubico page where a new API key can be generated in the admin menu.

This link -> https://upgrade.yubico.com/getapikey/

**Comment by sullenx** [comment]
@Tarry91  I added the links and more context. I also added the Yubico Verification server address. 

Check it out, so we can close the issue.

**Comment by Tarry91** [comment]
@sullenx Looks very nice and i especially like the option to test an OTP. Works perfectly on Firefox 57.
