### ISSUE TITLE
Publish App to nextcloud app store

### ISSUE THREAD

**Issue by Tarry91** [jaark/twofactor_yubikey#8]
I love the app and what has been done with it in the last week!
I believe it is ready to be open for a broader audience. We should publish it in the nextcloud app store. This is the first place people are looking for apps and it also lets people update there app easily.

The steps are outlined here -> https://nextcloudappstore.readthedocs.io/en/latest/developer.html

**Comment by sullenx** [comment]
@Tarry91 @jaark 

I see in order to put the App in the store, we must create a certificate. Since @jaark is the owner of the project, would you like to put the app in the store?

**Comment by Tarry91** [comment]
Is there any news regarding this issue? Did @jaark reach out to you?

**Comment by jaark** [comment]
I think that the best solution would be to transfer ownership of this repo. Work and other commitments mean I get very little time to do much with this. (I'm actually still running NC11!). I think I suggested this to @sullenx before.

**Comment by jaark** [comment]
OK, it seems I might have a bit of time for this (famous last words).

Requested a signing certificate.

**Comment by jaark** [comment]
At long last...
https://apps.nextcloud.com/apps/twofactor_yubikey
